services:
  notebook-tts-bark:
    build:
      context: text_to_speech_api
      dockerfile: Dockerfile_notebook
    container_name: text_to_speech_bark_GPU
    command: jupyter lab --ip=0.0.0.0 --allow-root --port=8901
    environment:
      - HF_HOME=/model
      - XDG_CACHE_HOME=/model
      - SUNO_OFFLOAD_CPU=True
      - SUNO_USE_SMALL_MODELS=True
    ports:
      - 8901:8901
    volumes:
      - $PWD/model:/model
      - $PWD:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  tts-api:
    build:
      context: text_to_speech_api
      dockerfile: Dockerfile_tts_api
    container_name: tts_api
    environment:
      - HF_HOME=/model
    ports:
      - 5000:5000
    volumes:
      - $PWD/model:/model
      - $PWD/text_to_speech_api:/app
